export const Categories = {
    MainMenu: ["Glasses"," Fitness & Gym","Travel & Outdoor","Backpack","Health & Beauty","Winter Collection"],
    electronics: ["Trimmer & Epilators", "Body Massager"],
    solar: ["Solar Lights", "Torch & Lights"],
    watches: ["Smart Watches", "Digital Watches"],
    wallets: ["Gents Wallets", "Ladies Wallets"],
    other: ["Accessories", "Gifts"],
  };
  // Mobile menu items
  export const mobileMenuItems = [
    'WINTER SALE',
    'ADVENTURE',
    'LADIES WALLETS',
    'GENTS WALLETS',
    'WATCHES',
    'HAIR TRIMMERS',
    'SMART WATCHES',
    'BAGS',
    'SOLAR LIGHTS',
    'TORCH LIGHTS',
    'FITNESS & GYM',
    'HOME & KITCHEN',
    'BEAUTY & COSMETICS',
    'MOBILE ACCESSORIES',
    'MISCELLANEOUS',
    'GLASSES',
    'TOOLKIT',
    'BODY MASSAGER',
    'BELTS',
    'BINOCULARS',
    'Gaming Accessories',
    'Kids',
    'PSL Shirts',
    'Catalog',
  ];